name: JavaDocs

on:
  push:
    branches:
      - main

jobs:
  javadocs:
    runs-on: ubuntu-latest

    permissions:
      pages: write      # needed to publish to GitHub Pages
      id-token: write   # required for GitHub Pages deployment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Generate Javadocs
        run: mvn -B javadoc:javadoc -Pcentral

      - name: Build Docs
        run:  sh ./docs/build.sh

      - name: Copy Javadocs into docs
        run: cp -r target/site/apidocs ./docs/.hyperbook/out/javadocs

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Docs artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs/.hyperbook

      - name: Deploy Javadocs to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
